languageCode = "en-US"
title = "YouShouldHaveBoughtStocks.com"
publishdir = "public"
canonifyURLs = true
googleAnalytics = "UA-126743160-3"
baseURL = "https://youshouldhaveboughtstocks.com"
staticDir = ["static", "node_modules/@fortawesome/fontawesome-free/webfonts"]

[params]
    subtitle = "You Should Have Bought Stocks"
    description = "YouShouldHaveBoughtStocks.com - why you should have bought stocks at IPO"
    author = "Niek van der Maas"
    favicon = "/favicon.png"

 [author]
     name = "Niek van der Maas"
     email = "mail@niekvandermaas.nl"